version: 1

units:
  length: m
  time: s
  temperature: K
  mass: kg
  force: N

domain:
  dim: 3
  bounds:
    x: [0.0, 1000.0]
    y: [0.0, 1000.0]
    z: [0.0, 500.0]      # z вверх/вниз - надо смотреть в коде, здесь просто диапазон
  time:
    t0: 0.0
    t1: 2.0              # Tmax
  output_times:
    kind: linspace
    n: 401               # для вывода/валидации (PINN решает непрерывно)

material:
  isotropic: true

  # Как задаём поля: "constant" | "layers" | "grid" | "function"
  parameterization: layers

  # Общие параметры (если constant)
  constants:
    rho: 2600.0          # kg/m^3
    lame_lambda: 2.0e10  # Pa
    lame_mu: 1.2e10      # Pa
    k: 2.5               # W/(m*K)
    C: 2.2e6             # J/(m^3*K)  (объёмная теплоёмкость rho*cp)
    gamma: 1.0e6         # (единицы зависят от вашей модели)
    T0: 293.15           # K

  # Пример слоистой модели по z
  layers:
    axis: z
    # интервал задаётся в координатах домена
    # параметры в каждом слое могут быть любыми из списка: rho, lame_lambda, lame_mu, k, C, gamma, T0
    items:
      - z_range: [0.0, 200.0]
        rho: 2400.0
        lame_lambda: 1.8e10
        lame_mu: 1.0e10
        k: 2.0
        C: 2.0e6
        gamma: 0.8e6
      - z_range: [200.0, 500.0]
        rho: 2700.0
        lame_lambda: 2.2e10
        lame_mu: 1.4e10
        k: 3.0
        C: 2.4e6
        gamma: 1.1e6

initial_conditions:
  displacement_u:
    kind: constant
    value: [0.0, 0.0, 0.0]     # u_x, u_y, u_z
  velocity_udot:
    kind: constant
    value: [0.0, 0.0, 0.0]
  temperature_T:
    kind: constant
    value: 293.15

boundary_conditions:
  mechanics:
    # boundary selector: x0, x1, y0, y1, z0, z1 (грани бокса)
    - name: free_surface
      boundary: z1
      type: traction
      value:
        kind: constant
        value: [0.0, 0.0, 0.0]  # sigma*n = 0

    - name: absorbing_sides
      boundary: [x0, x1, y0, y1, z0]
      type: absorbing
      model: first_order        # "first_order" | "pml" (если будет реализован)
      params:
        strength: 1.0           # безразмерный коэффициент (подбирается)

  heat:
    - name: fixed_temperature_top
      boundary: z1
      type: dirichlet
      value:
        kind: constant
        value: 293.15

    - name: insulated_sides
      boundary: [x0, x1, y0, y1, z0]
      type: neumann_flux
      value:
        kind: constant
        value: 0.0              # -k dT/dn = 0

sources:
  # Набор сценариев. Каждый сценарий — отдельный прогон/батч в обучении или отдельная задача.
  scenarios:

    - id: s1_point_ricker
      description: "Точечный (локальный) импульс Ricker в объёме"
      mechanics:
        type: body_force
        spatial:
          kind: gaussian
          center: [500.0, 500.0, 250.0]
          radius: 25.0           # м (сигма/эффективный радиус — оговорите в коде)
        temporal:
          kind: ricker
          f0: 15.0               # Гц
          t0: 0.2                # с
        vector:
          kind: constant
          value: [0.0, 0.0, -1.0]  # направление
        amplitude: 1.0e7         # Н/м^3 (если body force)
      heat: null

    - id: s2_surface_pressure_pulse
      description: "Импульс давления на площадке на верхней поверхности"
      mechanics:
        type: boundary_traction
        boundary: z1
        patch:
          kind: circle
          center: [300.0, 300.0]   # координаты на грани (x,y)
          radius: 40.0
        traction:
          kind: normal_pressure
          amplitude: 5.0e6         # Па
          temporal:
            kind: half_sine
            t_start: 0.1
            duration: 0.05
      heat: null

    - id: s3_harmonic_vibrator
      description: "Гармоническое возбуждение (вибратор) на площадке"
      mechanics:
        type: boundary_traction
        boundary: z1
        patch:
          kind: rectangle
          center: [700.0, 700.0]
          size: [60.0, 60.0]       # (dx, dy)
        traction:
          kind: vector
          direction: [0.0, 0.0, -1.0]
          amplitude: 1.0e6         # Па
          temporal:
            kind: sine
            f: 10.0                # Гц
            phase: 0.0
            envelope:
              kind: tukey
              alpha: 0.2
              t_start: 0.1
              t_end: 1.5
      heat: null

    - id: s4_shear_pulse
      description: "Сдвиговый импульс (shear) в объёме"
      mechanics:
        type: body_force
        spatial:
          kind: gaussian
          center: [500.0, 700.0, 200.0]
          radius: 30.0
        temporal:
          kind: gaussian_pulse
          t0: 0.25
          sigma: 0.02
        vector:
          kind: constant
          value: [1.0, 0.0, 0.0]   # shear по x
        amplitude: 8.0e6
      heat: null

    - id: s5_thermal_spot
      description: "Термический импульс (если добавляете Q(x,t) в тепловое уравнение)"
      mechanics: null
      heat:
        type: volumetric_heat_source
        spatial:
          kind: gaussian
          center: [500.0, 500.0, 250.0]
          radius: 40.0
        temporal:
          kind: square
          t_start: 0.2
          duration: 0.1
        amplitude: 2.0e7           # Вт/м^3 (Q)
        note: "Требует добавления +Q в уравнение тепла"

observations:
  enabled: false
  sensors:
    - id: rec1
      position: [100.0, 100.0, 500.0]
      measures: [u_z]             # u_x,u_y,u_z, T, etc.
    - id: rec2
      position: [900.0, 900.0, 500.0]
      measures: [u_z]
  data_files: []                  # пути, если есть реальные записи
  noise_std: {}                   # например {u_z: 1e-6, T: 0.1}

pinn:
  # Что подаём на вход сети
  inputs: [x, y, z, t]            # базово
  # inputs: [x, y, z, t, rho, lame_lambda, lame_mu, k, C, gamma]

  outputs: [u_x, u_y, u_z, T]

  sampling:
    collocation:
      n_interior: 200000
      strategy: latin_hypercube
    boundary:
      n: 50000
    initial:
      n: 50000
    per_scenario_weight: true     # обучать на смеси сценариев

  loss_weights:
    motion: 1.0
    heat: 1.0
    bc: 10.0
    ic: 10.0
    data: 1.0

  normalization:
    # важно для стабильности обучения
    x_scale: 1000.0
    t_scale: 1.0
    u_scale: 1e-3
    T_scale: 1.0

  training:
    optimizer: adam
    lr: 1.0e-3
    steps: 200000
    # опционально:
    # second_stage: lbfgs
